/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeModal: typeof import('./src/components/HomeModal.vue')['default']
    IdenficatorModal: typeof import('./src/components/IdenficatorModal.vue')['default']
    InfoModal: typeof import('./src/components/InfoModal.vue')['default']
    LivenessModal: typeof import('./src/components/LivenessModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StreamModal: typeof import('./src/components/StreamModal.vue')['default']
    UzCard: typeof import('./src/components/UzCard.vue')['default']
  }
}
