version: "3.4"
services:
  frontend:
    container_name: identity
    image: identity:latest
    restart: on-failure
    build:
      context: . # Context will be the project root
      dockerfile: ./Dockerfile
      args:
        version: 1.0.0-SNAPSHOT
    ports:
      - 8003:80
    volumes:
      - ./:/app